!pip install numpy

In [6]:
import numpy as np

In [13]:
np.array([1,254,3,54,342,23,34])

array([  1, 254,   3,  54, 342,  23,  34])

## Numpy library (Numerical in python)
NumPy is a Python library for working with numbers and arrays.

# Array
Array is a collection of Homogeneous elements(Same data type)
it stores values in a contiguous memmory

In [2]:
#### Types of methods to Create an Array
# arraym arange, linspace

In [4]:
import numpy as np

In [6]:
arr = np.array([1,243,5,6,7,45])
arr

array([  1, 243,   5,   6,   7,  45])

In [7]:
arr = np.arange(1,21,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
arr = np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr = np.linspace(0.5 , 5 , 10) 
arr

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [10]:
arr = np.linspace(1,10,10) 
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
# arr = np.linspace( start_value , stop_value , number_of_elements )  
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
# Random values in array  (random)
arr = np.random.randint(10 , 100 , 10)
arr

array([92, 70, 71, 14, 21, 92, 74, 41, 76, 35], dtype=int32)

#### Array's Dimension
- 0th Dimension
- 1st Dimension
- 2nd Dimension
- 3rd Dimension
.
.
.
- Multi Dimension
#### Types
- 0th Dimension
  - np.array(34)
- 1st Dimension
  - np.array([34,78,90,87,54])
- 2nd Dimension
  - np.array([[23,45,65],[23,45,65]])

In [18]:
arr = np.array(23)
print(arr)
print(arr.shape)
print(arr.ndim)

23
()
0


In [19]:
arr = np.array([23,45,67,90])
print(arr)
print(arr.shape)
print(arr.ndim)

[23 45 67 90]
(4,)
1


In [20]:
arr = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
